resilience4j.circuitbreaker.instances:
  cinet-server:
    slidingWindowType: COUNT_BASED
    slidingWindowSize: 4
    failureRateThreshHold: 50f
    slowCallRateThreshold: 50f
    slowCallDurationThreshold: 3s
    permittedNumberOfCallsInHalfOpenState: 2
    waitDurationInOpenState: 5s
    exponentialBackoffMultiplier: 2
    enableExponentialBackoff: true
    writableStackTraceEnabled: false
    automaticTransitionFromOpenToHalfOpenEnabled: true
